/** KPI library, alerts, reports, saved views and activity feed. */

import { HEADLINE } from "./aggregates";
import { CURRENT, MONTHLY } from "./datasets";
import { round } from "./random";

export type KpiStatus = "On Track" | "At Risk" | "Critical";

export interface KpiDefinition {
  id: string;
  name: string;
  category: "Finance" | "Sales" | "Customers" | "Operations" | "Marketing" | "Workforce";
  value: number;
  target: number;
  unit: "currency" | "percent" | "number" | "score" | "days";
  owner: string;
  frequency: "Monthly" | "Weekly" | "Quarterly";
  definition: string;
  source: string;
  history: number[];
}

function historyFor(selector: (row: (typeof MONTHLY)[number]) => number) {
  return MONTHLY.slice(-12).map((row) => round(selector(row), 2));
}

export const KPIS: KpiDefinition[] = [
  {
    id: "kpi-revenue",
    name: "Monthly Recurring Revenue",
    category: "Finance",
    value: CURRENT.revenue,
    target: 4_600_000,
    unit: "currency",
    owner: "Elena Ferraro",
    frequency: "Monthly",
    definition: "Recognised subscription and services revenue for the closed accounting period.",
    source: "Finance ledger · closed period",
    history: historyFor((row) => row.revenue),
  },
  {
    id: "kpi-gross-margin",
    name: "Gross Margin",
    category: "Finance",
    value: CURRENT.grossMargin,
    target: 66,
    unit: "percent",
    owner: "Elena Ferraro",
    frequency: "Monthly",
    definition: "Revenue less direct cost of delivery, expressed as a percentage of revenue.",
    source: "Finance ledger · cost allocation model",
    history: historyFor((row) => row.grossMargin),
  },
  {
    id: "kpi-net-margin",
    name: "Net Margin",
    category: "Finance",
    value: CURRENT.netMargin,
    target: 27,
    unit: "percent",
    owner: "Tomas Lindqvist",
    frequency: "Monthly",
    definition: "Operating profit after all operating expenses divided by total revenue.",
    source: "Finance ledger · consolidated",
    history: historyFor((row) => row.netMargin),
  },
  {
    id: "kpi-cash-flow",
    name: "Operating Cash Flow",
    category: "Finance",
    value: CURRENT.cashFlow,
    target: 900_000,
    unit: "currency",
    owner: "Tomas Lindqvist",
    frequency: "Monthly",
    definition: "Net cash generated by operating activities during the period.",
    source: "Treasury reconciliation",
    history: historyFor((row) => row.cashFlow),
  },
  {
    id: "kpi-aov",
    name: "Average Order Value",
    category: "Sales",
    value: CURRENT.averageOrderValue,
    target: 1_850,
    unit: "currency",
    owner: "Mira Nakamura",
    frequency: "Monthly",
    definition: "Total booked revenue divided by the number of closed orders in the period.",
    source: "Order management extract",
    history: historyFor((row) => row.averageOrderValue),
  },
  {
    id: "kpi-pipeline",
    name: "Qualified Pipeline",
    category: "Sales",
    value: CURRENT.pipeline,
    target: 15_000_000,
    unit: "currency",
    owner: "Viktor Petrov",
    frequency: "Weekly",
    definition: "Open opportunity value weighted by stage across all regions.",
    source: "Revenue operations model",
    history: historyFor((row) => row.pipeline),
  },
  {
    id: "kpi-conversion",
    name: "Lead Conversion Rate",
    category: "Marketing",
    value: CURRENT.conversionRate,
    target: 8,
    unit: "percent",
    owner: "Priya Sandoval",
    frequency: "Monthly",
    definition: "New customers created divided by marketing qualified leads in the period.",
    source: "Campaign attribution model",
    history: historyFor((row) => row.conversionRate),
  },
  {
    id: "kpi-cac",
    name: "Customer Acquisition Cost",
    category: "Marketing",
    value: CURRENT.cac,
    target: 4_200,
    unit: "currency",
    owner: "Priya Sandoval",
    frequency: "Monthly",
    definition: "Blended sales and marketing investment divided by new customers acquired.",
    source: "Campaign attribution model",
    history: historyFor((row) => row.cac),
  },
  {
    id: "kpi-ltv",
    name: "Customer Lifetime Value",
    category: "Customers",
    value: CURRENT.ltv,
    target: 21_000,
    unit: "currency",
    owner: "Clara Dumont",
    frequency: "Quarterly",
    definition: "Projected gross profit contributed by an average customer across their lifetime.",
    source: "Customer analytics model",
    history: historyFor((row) => row.ltv),
  },
  {
    id: "kpi-churn",
    name: "Monthly Churn Rate",
    category: "Customers",
    value: CURRENT.churnRate,
    target: 1.8,
    unit: "percent",
    owner: "Clara Dumont",
    frequency: "Monthly",
    definition: "Customers lost during the period as a share of the opening customer base.",
    source: "Customer lifecycle warehouse",
    history: historyFor((row) => row.churnRate),
  },
  {
    id: "kpi-retention",
    name: "Logo Retention",
    category: "Customers",
    value: CURRENT.retentionRate,
    target: 98,
    unit: "percent",
    owner: "Hugo Osei",
    frequency: "Monthly",
    definition: "Share of customers retained across consecutive periods.",
    source: "Customer lifecycle warehouse",
    history: historyFor((row) => row.retentionRate),
  },
  {
    id: "kpi-nps",
    name: "Net Promoter Score",
    category: "Customers",
    value: CURRENT.nps,
    target: 52,
    unit: "score",
    owner: "Hugo Osei",
    frequency: "Quarterly",
    definition: "Promoters less detractors from the quarterly relationship survey.",
    source: "Voice of customer program",
    history: historyFor((row) => row.nps),
  },
  {
    id: "kpi-efficiency",
    name: "Operational Efficiency Index",
    category: "Operations",
    value: CURRENT.efficiency,
    target: 90,
    unit: "percent",
    owner: "Jonas Rasmussen",
    frequency: "Monthly",
    definition: "Composite index of throughput, utilisation and rework across fulfilment.",
    source: "Operations data mart",
    history: historyFor((row) => row.efficiency),
  },
  {
    id: "kpi-fulfillment",
    name: "Order Fulfilment Rate",
    category: "Operations",
    value: CURRENT.fulfillmentRate,
    target: 97.5,
    unit: "percent",
    owner: "Jonas Rasmussen",
    frequency: "Weekly",
    definition: "Orders fulfilled complete and on first attempt as a share of total orders.",
    source: "Operations data mart",
    history: historyFor((row) => row.fulfillmentRate),
  },
  {
    id: "kpi-delivery",
    name: "On-Time Delivery",
    category: "Operations",
    value: CURRENT.onTimeDelivery,
    target: 96,
    unit: "percent",
    owner: "Ines Moretti",
    frequency: "Weekly",
    definition: "Deliveries completed within the committed service window.",
    source: "Logistics tracking extract",
    history: historyFor((row) => row.onTimeDelivery),
  },
  {
    id: "kpi-inventory",
    name: "Inventory Turnover",
    category: "Operations",
    value: CURRENT.inventoryTurnover,
    target: 7.2,
    unit: "number",
    owner: "Ines Moretti",
    frequency: "Monthly",
    definition: "Cost of goods delivered divided by average inventory held.",
    source: "Supply chain warehouse",
    history: historyFor((row) => row.inventoryTurnover),
  },
  {
    id: "kpi-headcount",
    name: "Total Headcount",
    category: "Workforce",
    value: CURRENT.headcount,
    target: 720,
    unit: "number",
    owner: "Zara Whitfield",
    frequency: "Monthly",
    definition: "Active employees on the last calendar day of the period.",
    source: "People operations register",
    history: historyFor((row) => row.headcount),
  },
  {
    id: "kpi-turnover",
    name: "Annualised Turnover",
    category: "Workforce",
    value: CURRENT.turnoverRate,
    target: 11,
    unit: "percent",
    owner: "Zara Whitfield",
    frequency: "Monthly",
    definition: "Voluntary and involuntary departures annualised against average headcount.",
    source: "People operations register",
    history: historyFor((row) => row.turnoverRate),
  },
  {
    id: "kpi-productivity",
    name: "Productivity Index",
    category: "Workforce",
    value: CURRENT.productivityIndex,
    target: 110,
    unit: "number",
    owner: "Soren Engel",
    frequency: "Monthly",
    definition: "Output per full-time equivalent indexed against the baseline period.",
    source: "Workforce analytics model",
    history: historyFor((row) => row.productivityIndex),
  },
  {
    id: "kpi-satisfaction",
    name: "Customer Satisfaction",
    category: "Customers",
    value: CURRENT.satisfaction,
    target: 4.5,
    unit: "score",
    owner: "Hugo Osei",
    frequency: "Monthly",
    definition: "Mean rating from post-interaction satisfaction surveys, on a five point scale.",
    source: "Voice of customer program",
    history: historyFor((row) => row.satisfaction),
  },
];

const LOWER_IS_BETTER = new Set(["kpi-churn", "kpi-cac", "kpi-turnover"]);

export function kpiVariance(kpi: KpiDefinition) {
  const raw = ((kpi.value - kpi.target) / kpi.target) * 100;
  return round(LOWER_IS_BETTER.has(kpi.id) ? -raw : raw, 1);
}

export function kpiStatus(kpi: KpiDefinition): KpiStatus {
  const variance = kpiVariance(kpi);
  if (variance >= -2) return "On Track";
  if (variance >= -10) return "At Risk";
  return "Critical";
}

export function kpiTrend(kpi: KpiDefinition) {
  const [first] = kpi.history;
  const last = kpi.history[kpi.history.length - 1];
  if (!first) return 0;
  const raw = ((last - first) / Math.abs(first)) * 100;
  return round(LOWER_IS_BETTER.has(kpi.id) ? -raw : raw, 1);
}

/* Alerts ------------------------------------------------------------ */

export type AlertSeverity = "Critical" | "High" | "Medium" | "Low" | "Info";

export interface AnalyticsAlert {
  id: string;
  title: string;
  category: "Finance" | "Sales" | "Customers" | "Operations" | "Marketing" | "Workforce";
  severity: AlertSeverity;
  date: string;
  description: string;
  status: "Open" | "Acknowledged" | "Resolved";
  metric: string;
  change: number;
}

export const ALERTS: AnalyticsAlert[] = [
  {
    id: "ALT-2041",
    title: "Revenue below target in Latin America",
    category: "Finance",
    severity: "Critical",
    date: "2026-08-28",
    description:
      "Latin America closed the period 12.4% under its revenue commitment, driven by two enterprise renewals slipping into the next quarter.",
    status: "Open",
    metric: "Regional revenue",
    change: -12.4,
  },
  {
    id: "ALT-2040",
    title: "Expense variance detected in Cloud Infrastructure",
    category: "Finance",
    severity: "High",
    date: "2026-08-26",
    description:
      "Cloud infrastructure spend exceeded the approved budget envelope by 9.1% following the data platform capacity expansion.",
    status: "Acknowledged",
    metric: "Budget variance",
    change: 9.1,
  },
  {
    id: "ALT-2039",
    title: "Customer churn increased in the Growth segment",
    category: "Customers",
    severity: "High",
    date: "2026-08-24",
    description:
      "Growth segment churn rose to 3.2% against a 1.9% baseline. Sixteen accounts lapsed without a renewal conversation logged.",
    status: "Open",
    metric: "Churn rate",
    change: 1.3,
  },
  {
    id: "ALT-2038",
    title: "Inventory turnover declined for Integration Hub",
    category: "Operations",
    severity: "Medium",
    date: "2026-08-21",
    description:
      "Turnover for the Integration Hub category fell to 5.4, below the 7.2 target, with eleven SKUs sitting under their reorder point.",
    status: "Acknowledged",
    metric: "Inventory turnover",
    change: -1.8,
  },
  {
    id: "ALT-2037",
    title: "Conversion rate improved on Partner Network",
    category: "Marketing",
    severity: "Info",
    date: "2026-08-19",
    description:
      "Partner Network conversion improved 1.9 points after the co-marketing motion launched, now the second strongest channel by ROI.",
    status: "Resolved",
    metric: "Conversion rate",
    change: 1.9,
  },
  {
    id: "ALT-2036",
    title: "Operational efficiency changed in Asia Pacific",
    category: "Operations",
    severity: "Medium",
    date: "2026-08-17",
    description:
      "Efficiency index moved 2.6 points across Asia Pacific fulfilment centres following the routing model change in Singapore.",
    status: "Open",
    metric: "Efficiency index",
    change: 2.6,
  },
  {
    id: "ALT-2035",
    title: "Pipeline coverage below threshold for Q4",
    category: "Sales",
    severity: "High",
    date: "2026-08-15",
    description:
      "Weighted pipeline coverage for the coming quarter sits at 2.6x against a 3.0x guardrail in the Enterprise segment.",
    status: "Open",
    metric: "Pipeline coverage",
    change: -13.3,
  },
  {
    id: "ALT-2034",
    title: "Voluntary turnover rising in Engineering",
    category: "Workforce",
    severity: "Medium",
    date: "2026-08-12",
    description:
      "Engineering turnover reached 13.8% annualised, 2.8 points above plan, concentrated in the platform reliability group.",
    status: "Acknowledged",
    metric: "Turnover rate",
    change: 2.8,
  },
  {
    id: "ALT-2033",
    title: "On-time delivery recovered in Europe",
    category: "Operations",
    severity: "Low",
    date: "2026-08-09",
    description:
      "European on-time delivery returned above the 96% service commitment after the Rotterdam carrier reallocation.",
    status: "Resolved",
    metric: "On-time delivery",
    change: 3.4,
  },
  {
    id: "ALT-2032",
    title: "Average order value trending above plan",
    category: "Sales",
    severity: "Info",
    date: "2026-08-06",
    description:
      "Average order value has grown for five consecutive periods, led by Enterprise tier attachments on the Analytics Suite.",
    status: "Resolved",
    metric: "Average order value",
    change: 6.8,
  },
  {
    id: "ALT-2031",
    title: "Marketing ROI dispersion across channels",
    category: "Marketing",
    severity: "Medium",
    date: "2026-08-03",
    description:
      "Return on marketing investment varies by more than 140 points between the strongest and weakest channel this period.",
    status: "Open",
    metric: "Marketing ROI",
    change: -4.2,
  },
  {
    id: "ALT-2030",
    title: "Support ticket volume above seasonal band",
    category: "Operations",
    severity: "Low",
    date: "2026-07-31",
    description:
      "Support volume exceeded the seasonal upper band by 7%, correlated with the Security Layer release window.",
    status: "Resolved",
    metric: "Support tickets",
    change: 7,
  },
];

/* Reports ----------------------------------------------------------- */

export interface ReportSection {
  id: string;
  title: string;
  summary: string;
  points: string[];
}

export interface ReportDefinition {
  id: string;
  name: string;
  category: "Executive" | "Finance" | "Sales" | "Customers" | "Operations" | "Marketing" | "Workforce";
  owner: string;
  updated: string;
  views: number;
  status: "Published" | "Draft" | "Scheduled" | "Archived";
  description: string;
  schedule: string;
  audience: string;
  sections: ReportSection[];
}

export const REPORTS: ReportDefinition[] = [
  {
    id: "executive-performance-review",
    name: "Executive Performance Review",
    category: "Executive",
    owner: "Elena Ferraro",
    updated: "2026-08-29",
    views: 1_842,
    status: "Published",
    description: "Board-level view of revenue, profitability, customers, operations, workforce, risks and upside.",
    schedule: "Monthly · first business day",
    audience: "Board and executive committee",
    sections: [
      {
        id: "executive-summary",
        title: "Executive Summary",
        summary:
          "The business closed the period ahead of plan on revenue and margin, with customer growth compounding while acquisition cost held flat.",
        points: [
          "Trailing twelve month revenue grew against the prior comparable period on broad regional participation.",
          "Net margin expanded as the cost base grew more slowly than revenue for the fifth consecutive period.",
          "Latin America is the single material shortfall against commitment and is under an active recovery plan.",
        ],
      },
      {
        id: "revenue",
        title: "Revenue",
        summary:
          "Revenue growth is led by the Analytics Suite and Data Platform categories, with North America and Europe contributing the majority of absolute gain.",
        points: [
          "Analytics Suite remains the largest category by booked revenue.",
          "Average order value has increased for five consecutive periods on Enterprise tier attachments.",
          "Self-serve is the fastest growing channel from a small base.",
        ],
      },
      {
        id: "profitability",
        title: "Profitability",
        summary:
          "Gross margin improved on delivery automation while operating leverage held, despite an overrun in cloud infrastructure.",
        points: [
          "Gross margin trends above the prior year in every quarter of the trailing period.",
          "Cloud infrastructure is the only expense category materially above budget.",
          "Operating cash conversion remains healthy relative to reported profit.",
        ],
      },
      {
        id: "customers",
        title: "Customers",
        summary:
          "The customer base expanded while churn declined structurally, though the Growth segment showed a one-period deterioration.",
        points: [
          "Logo retention improved as lifecycle programs matured.",
          "Lifetime value to acquisition cost ratio remains comfortably above the internal guardrail.",
          "Growth segment churn requires intervention and is tracked as an open alert.",
        ],
      },
      {
        id: "operations",
        title: "Operations",
        summary:
          "Fulfilment and delivery both improved, while inventory turnover in one category fell below the operating target.",
        points: [
          "Order fulfilment rate improved steadily across the trailing twelve periods.",
          "On-time delivery recovered in Europe after the carrier reallocation.",
          "Integration Hub inventory turnover is below target with SKUs under their reorder point.",
        ],
      },
      {
        id: "workforce",
        title: "Workforce",
        summary:
          "Headcount grew in line with the hiring plan and productivity improved, with turnover concentrated in one engineering group.",
        points: [
          "Net headcount additions tracked the approved plan across the period.",
          "Productivity index continued its upward trend against the baseline.",
          "Engineering turnover is above plan and under review by People Operations.",
        ],
      },
      {
        id: "risks",
        title: "Risks",
        summary:
          "Three risks carry executive attention this period, all with a named owner and a mitigation in flight.",
        points: [
          "Regional revenue concentration exposes the plan to Latin America recovery timing.",
          "Cloud infrastructure cost growth may compress margin if capacity is not rebalanced.",
          "Pipeline coverage in the Enterprise segment sits below the internal guardrail for the coming quarter.",
        ],
      },
      {
        id: "opportunities",
        title: "Opportunities",
        summary: "Three opportunities offer measurable upside within the next two planning periods.",
        points: [
          "Partner Network conversion gains suggest room to expand co-marketing investment.",
          "Enterprise tier attachment rates support a structured upsell motion in Europe.",
          "Self-serve onboarding improvements can lower blended acquisition cost further.",
        ],
      },
    ],
  },
  {
    id: "revenue-performance-monthly",
    name: "Revenue Performance Monthly",
    category: "Finance",
    owner: "Tomas Lindqvist",
    updated: "2026-08-27",
    views: 1_204,
    status: "Published",
    description: "Revenue, margin and budget variance by region, category and channel for the closed period.",
    schedule: "Monthly · day three",
    audience: "Finance leadership",
    sections: [
      {
        id: "executive-summary",
        title: "Executive Summary",
        summary: "Revenue finished ahead of budget with margin expansion in four of five regions.",
        points: [
          "Budget variance is positive at consolidated level.",
          "Latin America is the sole negative regional variance.",
          "Category mix shifted toward higher margin software revenue.",
        ],
      },
      {
        id: "revenue",
        title: "Revenue",
        summary: "Regional and category revenue detail with prior period comparison.",
        points: [
          "North America contributed the largest absolute revenue gain.",
          "Data Platform grew fastest among the major categories.",
          "Marketplace channel revenue remains immaterial to the consolidated result.",
        ],
      },
      {
        id: "profitability",
        title: "Profitability",
        summary: "Margin bridge from gross to net with expense category detail.",
        points: [
          "Gross margin improved period over period.",
          "Payroll remains the largest single expense category.",
          "Flagged expenses are within the tolerance threshold by value.",
        ],
      },
    ],
  },
  {
    id: "sales-pipeline-review",
    name: "Sales Pipeline Review",
    category: "Sales",
    owner: "Viktor Petrov",
    updated: "2026-08-25",
    views: 968,
    status: "Published",
    description: "Weighted pipeline, stage conversion and regional quota attainment across the selling organisation.",
    schedule: "Weekly · Monday",
    audience: "Revenue leadership",
    sections: [
      {
        id: "executive-summary",
        title: "Executive Summary",
        summary: "Pipeline value grew while coverage in the Enterprise segment slipped below the guardrail.",
        points: [
          "Total weighted pipeline increased period over period.",
          "Enterprise coverage sits below the internal 3.0x guardrail.",
          "Negotiation stage aging improved after the deal desk change.",
        ],
      },
      {
        id: "revenue",
        title: "Revenue",
        summary: "Closed won value by region, segment and product category.",
        points: [
          "North America leads closed won value.",
          "Analytics Suite is attached to the majority of enterprise wins.",
          "Average deal size increased across all segments except Startup.",
        ],
      },
    ],
  },
  {
    id: "customer-health-index",
    name: "Customer Health Index",
    category: "Customers",
    owner: "Clara Dumont",
    updated: "2026-08-23",
    views: 754,
    status: "Published",
    description: "Retention, churn risk, lifetime value and satisfaction across every customer segment.",
    schedule: "Monthly · day five",
    audience: "Customer success leadership",
    sections: [
      {
        id: "executive-summary",
        title: "Executive Summary",
        summary: "Overall health improved while the Growth segment deteriorated for a single period.",
        points: [
          "Logo retention improved against the prior period.",
          "High churn risk accounts are concentrated in the Growth segment.",
          "Satisfaction scores trend gently upward across the trailing year.",
        ],
      },
      {
        id: "customers",
        title: "Customers",
        summary: "Segment level detail on base, revenue contribution and risk distribution.",
        points: [
          "Enterprise contributes the largest share of revenue per logo.",
          "Onboarding cohort conversion to Active improved.",
          "Churned logos remain a small share of the total base.",
        ],
      },
    ],
  },
  {
    id: "operations-scorecard",
    name: "Operations Scorecard",
    category: "Operations",
    owner: "Jonas Rasmussen",
    updated: "2026-08-22",
    views: 641,
    status: "Published",
    description: "Fulfilment, delivery, inventory and incident performance against operating commitments.",
    schedule: "Weekly · Friday",
    audience: "Operations leadership",
    sections: [
      {
        id: "executive-summary",
        title: "Executive Summary",
        summary: "Service levels improved while one inventory category fell below its turnover target.",
        points: [
          "Fulfilment rate improved for the third consecutive period.",
          "Delayed orders remain a small share of total volume.",
          "Integration Hub inventory turnover is below target.",
        ],
      },
      {
        id: "operations",
        title: "Operations",
        summary: "Detailed operating metrics by process area.",
        points: [
          "Median delivery time sits inside the service window.",
          "Incident volume declined against the trailing average.",
          "Efficiency index improved across four of five regions.",
        ],
      },
    ],
  },
  {
    id: "marketing-attribution",
    name: "Marketing Attribution Review",
    category: "Marketing",
    owner: "Priya Sandoval",
    updated: "2026-08-20",
    views: 587,
    status: "Scheduled",
    description: "Channel return on investment, campaign performance and acquisition cost by segment.",
    schedule: "Monthly · day seven",
    audience: "Marketing leadership",
    sections: [
      {
        id: "executive-summary",
        title: "Executive Summary",
        summary: "Return on investment improved on the partner motion while paid search efficiency softened.",
        points: [
          "Partner Network delivered the strongest incremental return.",
          "Blended acquisition cost held roughly flat.",
          "Channel ROI dispersion widened and is tracked as an open alert.",
        ],
      },
    ],
  },
  {
    id: "workforce-analytics",
    name: "Workforce Analytics Review",
    category: "Workforce",
    owner: "Zara Whitfield",
    updated: "2026-08-18",
    views: 432,
    status: "Draft",
    description: "Headcount, hiring, turnover, attendance and productivity across every department.",
    schedule: "Monthly · day ten",
    audience: "People leadership",
    sections: [
      {
        id: "executive-summary",
        title: "Executive Summary",
        summary: "Hiring tracked plan while turnover concentrated in one engineering group.",
        points: [
          "Net additions matched the approved hiring plan.",
          "Engineering turnover exceeded plan.",
          "Attendance and engagement both held steady.",
        ],
      },
      {
        id: "workforce",
        title: "Workforce",
        summary: "Departmental detail on headcount, performance and productivity.",
        points: [
          "Engineering remains the largest department by headcount.",
          "Productivity improved across the majority of departments.",
          "Performance distribution narrowed against the prior period.",
        ],
      },
    ],
  },
  {
    id: "regional-revenue-breakdown",
    name: "Regional Revenue Breakdown",
    category: "Finance",
    owner: "Bastien Delacroix",
    updated: "2026-08-14",
    views: 396,
    status: "Published",
    description: "Revenue, margin and attainment by region and country with drill-down to customer level.",
    schedule: "Monthly · day four",
    audience: "Regional general managers",
    sections: [
      {
        id: "revenue",
        title: "Revenue",
        summary: "Regional contribution and country level detail.",
        points: [
          "North America and Europe together contribute the majority of revenue.",
          "Asia Pacific grew fastest in percentage terms.",
          "Latin America finished below commitment.",
        ],
      },
    ],
  },
  {
    id: "product-profitability",
    name: "Product Profitability Analysis",
    category: "Finance",
    owner: "Greta Halvorsen",
    updated: "2026-08-11",
    views: 318,
    status: "Published",
    description: "Product level revenue, margin and unit economics across the full catalogue.",
    schedule: "Quarterly",
    audience: "Product and finance",
    sections: [
      {
        id: "profitability",
        title: "Profitability",
        summary: "Margin distribution and revenue concentration across the catalogue.",
        points: [
          "The top ten products contribute a disproportionate share of revenue.",
          "Margin varies widely between software and services lines.",
          "Sunset products remain immaterial to the consolidated result.",
        ],
      },
    ],
  },
  {
    id: "quarterly-board-pack",
    name: "Quarterly Board Pack",
    category: "Executive",
    owner: "Elena Ferraro",
    updated: "2026-07-04",
    views: 2_311,
    status: "Archived",
    description: "Prior quarter board materials covering strategy, performance, risk and capital allocation.",
    schedule: "Quarterly",
    audience: "Board of directors",
    sections: [
      {
        id: "executive-summary",
        title: "Executive Summary",
        summary: "The prior quarter closed ahead of plan on revenue with margin in line with guidance.",
        points: [
          "All strategic initiatives remained on schedule.",
          "Capital allocation followed the approved framework.",
          "No material control findings were raised.",
        ],
      },
    ],
  },
];

export const EXECUTIVE_REPORT = REPORTS[0];

/* Saved views ------------------------------------------------------- */

export interface SavedView {
  id: string;
  name: string;
  module: string;
  href: string;
  description: string;
  owner: string;
  updated: string;
  shared: boolean;
  filters: string[];
}

export const SAVED_VIEWS: SavedView[] = [
  {
    id: "view-executive-overview",
    name: "Executive Overview",
    module: "Executive Dashboard",
    href: "/dimension-insight/dashboard",
    description: "Consolidated revenue, profit, customer and operating position for the executive committee.",
    owner: "Elena Ferraro",
    updated: "2026-08-30",
    shared: true,
    filters: ["Period: Last 12 months", "Region: All", "Currency: USD"],
  },
  {
    id: "view-sales-performance",
    name: "Sales Performance",
    module: "Sales Analytics",
    href: "/dimension-insight/analytics/sales",
    description: "Pipeline coverage, closed won value and regional attainment for the selling organisation.",
    owner: "Viktor Petrov",
    updated: "2026-08-29",
    shared: true,
    filters: ["Period: Last 6 months", "Segment: Enterprise, Mid-Market", "Stage: Open"],
  },
  {
    id: "view-financial-overview",
    name: "Financial Overview",
    module: "Finance Analytics",
    href: "/dimension-insight/analytics/finance",
    description: "Revenue, expense and margin position with budget variance by category.",
    owner: "Tomas Lindqvist",
    updated: "2026-08-28",
    shared: false,
    filters: ["Period: Fiscal year to date", "Entity: Consolidated"],
  },
  {
    id: "view-customer-health",
    name: "Customer Health",
    module: "Customer Analytics",
    href: "/dimension-insight/analytics/customers",
    description: "Retention, churn risk and lifetime value across every customer segment.",
    owner: "Clara Dumont",
    updated: "2026-08-27",
    shared: true,
    filters: ["Segment: All", "Health score: Below 70", "Status: Active"],
  },
  {
    id: "view-operations-monitor",
    name: "Operations Monitor",
    module: "Operations Analytics",
    href: "/dimension-insight/analytics/operations",
    description: "Fulfilment, delivery and inventory service levels against operating commitments.",
    owner: "Jonas Rasmussen",
    updated: "2026-08-26",
    shared: true,
    filters: ["Period: Last 90 days", "Region: All", "Status: Delayed"],
  },
  {
    id: "view-workforce-overview",
    name: "Workforce Overview",
    module: "Workforce Analytics",
    href: "/dimension-insight/analytics/workforce",
    description: "Headcount, hiring, turnover and productivity across every department.",
    owner: "Zara Whitfield",
    updated: "2026-08-24",
    shared: false,
    filters: ["Department: All", "Employment: Active"],
  },
];

/* Activity feed ----------------------------------------------------- */

export interface ActivityEntry {
  id: string;
  actor: string;
  action: string;
  target: string;
  time: string;
  type: "report" | "alert" | "view" | "kpi" | "export";
}

export const ACTIVITY: ActivityEntry[] = [
  {
    id: "act-1",
    actor: "Elena Ferraro",
    action: "published",
    target: "Executive Performance Review",
    time: "12 minutes ago",
    type: "report",
  },
  {
    id: "act-2",
    actor: "Viktor Petrov",
    action: "acknowledged",
    target: "Pipeline coverage below threshold for Q4",
    time: "48 minutes ago",
    type: "alert",
  },
  {
    id: "act-3",
    actor: "Clara Dumont",
    action: "updated",
    target: "Customer Health saved view",
    time: "1 hour ago",
    type: "view",
  },
  {
    id: "act-4",
    actor: "Tomas Lindqvist",
    action: "revised the target for",
    target: "Operating Cash Flow",
    time: "2 hours ago",
    type: "kpi",
  },
  {
    id: "act-5",
    actor: "Priya Sandoval",
    action: "exported",
    target: "Marketing Attribution Review",
    time: "3 hours ago",
    type: "export",
  },
  {
    id: "act-6",
    actor: "Jonas Rasmussen",
    action: "resolved",
    target: "On-time delivery recovered in Europe",
    time: "5 hours ago",
    type: "alert",
  },
  {
    id: "act-7",
    actor: "Zara Whitfield",
    action: "created a draft of",
    target: "Workforce Analytics Review",
    time: "Yesterday",
    type: "report",
  },
  {
    id: "act-8",
    actor: "Hugo Osei",
    action: "shared",
    target: "Operations Monitor saved view",
    time: "Yesterday",
    type: "view",
  },
];

export const HEADLINE_SNAPSHOT = HEADLINE;
